# Generated by Django 3.2.3 on 2021-07-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
                ('descripcion_categoria', models.CharField(max_length=150, verbose_name='Descripcion de la categoria')),
            ],
        ),
    ]
