# Generated by Django 3.2.3 on 2021-07-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion_categoria',
            field=models.CharField(max_length=150, verbose_name=' Descripcion de la categoria '),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=50, verbose_name=' Nombre de la categoria '),
        ),
    ]
